### ISSUE TITLE
Setting isFutureDate as true styles days incorrectly as today

### ISSUE THREAD

**Issue by AlanFoster** [melihmucuk/rn-date-range#2]
When configuring this component with `isFutureDate={false}` the `isToday` style is applied to all day options that are set as 'common', and happen before today: 

![image](https://cloud.githubusercontent.com/assets/1271782/25805541/fd19f52a-33f7-11e7-9d53-1f4a713ef692.png)

I wonder if there is a less lenient way of computing the `isToday` predicate? 🤔 

It may be possible to use something like:

```js
const isToday = status === 'common' && date.toDateString() === new Date().toDateString() ? {borderWidth: 1, borderRadius: 15, borderColor: '#004BBB'} : {}
```

But it may be a performance overhead to compute this on each render. It may be better to extract this logic out into the parent Component - and remove the inline styles too?

**Comment by melihmucuk** [comment]
You're right about performance, but it forked component. So, If I have free time, I will change it. Performance is not critical right now for me. @AlanFoster

**Comment by AlanFoster** [comment]
Thanks for the insight @melihmucuk :+1:
